DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS films_likes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS mpa_films;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS films;